/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "animaux.h"

animal* animals;
int * n;
char login_f[100]="login.txt";

int
main (int argc, char *argv[])
{
  GtkWidget *window1;
  GtkWidget *window2;
  GtkWidget *window3; 
  GtkWidget *window4;
  GtkWidget *window5;
  GtkWidget *window6;
  GtkWidget *window7;
  GtkWidget *window8;
  GtkWidget *window9;
  GtkWidget *window10;
  GtkWidget * UN;
  GtkWidget * MP;
  GtkWidget *checkbox;
	
char nomutilisateur[50]="";
char motdepasse[50]="";



#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  GdkColor color;


 // color.red=0x0000;
 // color.green=0x9000;
 // color.blue=0x9000;
 

  color.red=0x0000;
  color.green=0xC000;
  color.blue=0xC000;

  window1 = create_Lobby ();      gtk_widget_modify_bg(GTK_WIDGET(window1),GTK_STATE_NORMAL,&color);  
  gtk_widget_show (window1);

readData (nomutilisateur,motdepasse,login_f );
if (strcmp(nomutilisateur,"")!=0 && strcmp(motdepasse,"")!=0)
{
// Nom ENTRY TEXT
UN = lookup_widget(window1, "HLentryNomUtilisateur");
gtk_entry_set_text(GTK_ENTRY(UN),nomutilisateur);
// mot de passe ENTRY TEXT
MP = lookup_widget(window1, "HLentryPassword");
gtk_entry_set_text(GTK_ENTRY(MP),motdepasse);

//CHECKBOXES INITIALISATIONS
   checkbox=lookup_widget(window1,"HLcheckbuttonSauvegarderInfo");
   gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON(checkbox),TRUE);

}

  
  gtk_main ();
  return 0;
}

