/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Lobby (void);
GtkWidget* create_affichage_troupeaux (void);
GtkWidget* create_menu_proprietaire (void);
GtkWidget* create_menu_troupeau (void);
GtkWidget* create_ajouter_animal (void);
GtkWidget* create_modifier_animal (void);
GtkWidget* create_supprimer_animal (void);
GtkWidget* create_statistiques (void);
GtkWidget* create_nombre_de_troupeaux (void);
GtkWidget* create_creer_un_compte (void);
GtkWidget* create_AD_ajouter_equipement (void);
GtkWidget* create_AD_modifier_equipement (void);
GtkWidget* create_AD_supprimer_equipement (void);
GtkWidget* create_AD_afficher_equipement (void);
GtkWidget* create_AD_gestion_equipement (void);
GtkWidget* create_OA_ajout_client (void);
GtkWidget* create_OA_modifier_client (void);
GtkWidget* create_OA_supp_client (void);
GtkWidget* create_OA_menu_client (void);
GtkWidget* create_OA_Afficher_client (void);
GtkWidget* create_OA_Gestion_Absenteisme_client (void);
GtkWidget* create_HB_ajout_plante (void);
GtkWidget* create_HB_supp_plante (void);
GtkWidget* create_HB_modif_plante (void);
GtkWidget* create_HB_gestion_plante (void);
GtkWidget* create_HB_annee_plus_seche (void);
GtkWidget* create_HB_affichage (void);
GtkWidget* create_OA_Taux_dabsenteisme (void);
GtkWidget* create_TS_ajoutOuvrier (void);
GtkWidget* create_TS_menu_ouvrier (void);
GtkWidget* create_TS_modifierOuvrier (void);
GtkWidget* create_TS_supprimer_un_ouvrier (void);
GtkWidget* create_TS_afficher_les_ouvriers (void);
GtkWidget* create_TS_validation_de_presence (void);
GtkWidget* create_TS_meilleur_ouvrier (void);
GtkWidget* create_ZF_menu_capteur (void);
GtkWidget* create_ZF_ajouter_capteur (void);
GtkWidget* create_ZF_modifier_un_capteur (void);
GtkWidget* create_ZF_supprimer_un_capteur (void);
GtkWidget* create_ZF_afficher_les_capteurs (void);
GtkWidget* create_ZF_NDCADVA (void);
GtkWidget* create_AD_LA_MARQUE_ALMDCD (void);
